### PR TITLE
Fix on-submit after an error it did not display the "Loading..."

### PR DESCRIPTION
**Pull request by ChristopherTrimboli**

### CODE REVIEW

**Comment by avaer** [comment]
Hm I think the substance of this PR was accidentally destroyed in the merge from upstream.

Namely, this looks like the good commit: https://github.com/webmixedreality/exokit-home/pull/10/commits/8ad4bdeefdefc51e0eaa07f136d65bfdc04c9c10.

But then it's deleted in the merge fix: https://github.com/webmixedreality/exokit-home/pull/10/commits/e3d359509dc348bc4e510262cbaeac06c5ab4790.

**Comment by avaer** [comment]
I manually pulled out the substance of the good commit to `master`: https://github.com/webmixedreality/exokit-home/commit/0a68adae171ff367ee31fa3034b9e83dea742483. I.e. it's basically merged.

Was there anything else to this PR (which was good!)?

If there's nothing else then I think we can just close this as merged.

**Comment by ChristopherTrimboli** [comment]
Yeah it was just the one line to reset the error to false. Looks good.

**Comment by avaer** [comment]
:+1:

**Pull request closed without merging**
